### ISSUE TITLE
v-2023-06-07 release breaks on building musicbrainz-docker-index

### ISSUE THREAD

**Issue by brianredbeard** [metabrainz/musicbrainz-docker#252] opened 2023-06-14 18:54 UTC
Attempting to build release v-2023-06-07 currently fails due to missing directories in in the container musicbrainz-docker-index.

```bash
[core@filesharinghost musicbrainz-docker]$ git checkout -l v-2023-06-07 
Note: switching to 'v-2023-06-07'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 78d3a96 Upgrade MusicBrainz Server to v-2023-06-07
[core@filesharinghost musicbrainz-docker]$ git switch -c v-2023-06-07
Switched to a new branch 'v-2023-06-07'
[core@filesharinghost musicbrainz-docker]$ sudo docker-compose up --build -d 
[+] Building 8.5s (27/41)                                                                                                                              
 => [musicbrainz-docker_db:12 internal] load build definition from Dockerfile                                                                     0.3s
 => => transferring dockerfile: 91B                                                                                                               0.0s
 => [musicbrainz-docker_search:3.4.2 internal] load build definition from Dockerfile                                                              0.5s
 => => transferring dockerfile: 91B                                                                                                               0.0s
 => [musicbrainz-docker-indexer internal] load build definition from Dockerfile                                                                   0.7s
 => => transferring dockerfile: 91B                                                                                                               0.0s
 => [musicbrainz-docker-musicbrainz internal] load build definition from Dockerfile                                                               0.9s
 => => transferring dockerfile: 91B                                                                                                               0.0s
 => [musicbrainz-docker-mq internal] load build definition from Dockerfile                                                                        1.0s
 => => transferring dockerfile: 91B                                                                                                               0.0s
 => [musicbrainz-docker_db:12 internal] load .dockerignore                                                                                        1.0s
 => => transferring context: 2B                                                                                                                   0.0s
 => [musicbrainz-docker_search:3.4.2 internal] load .dockerignore                                                                                 1.1s
 => => transferring context: 2B                                                                                                                   0.0s
 => [musicbrainz-docker-indexer internal] load .dockerignore                                                                                      1.2s
 => => transferring context: 2B                                                                                                                   0.0s
 => [musicbrainz-docker-musicbrainz internal] load .dockerignore                                                                                  1.3s
 => => transferring context: 2B                                                                                                                   0.0s
 => [musicbrainz-docker-mq internal] load .dockerignore                                                                                           1.4s
 => => transferring context: 2B                                                                                                                   0.0s
 => [musicbrainz-docker_db:12 internal] load metadata for docker.io/library/postgres:12                                                           0.5s
 => [musicbrainz-docker_search:3.4.2 internal] load metadata for docker.io/metabrainz/mb-solr:3.4.2                                               0.4s
 => [musicbrainz-docker-indexer internal] load metadata for docker.io/metabrainz/python:2.7-20220421                                              0.6s
 => [musicbrainz-docker-musicbrainz internal] load metadata for docker.io/metabrainz/base-image:focal-1.0.0-alpha1                                0.7s
 => [musicbrainz-docker-mq internal] load metadata for docker.io/library/rabbitmq:3.6.16-management                                               1.0s
 => CANCELED [musicbrainz-docker_db:12 1/3] FROM docker.io/library/postgres:12@sha256:8e2e97c70f6bbb4dd7a45ff6130642587bc1d5587c2ba7154dbb0bf17a  5.5s
 => => resolve docker.io/library/postgres:12@sha256:8e2e97c70f6bbb4dd7a45ff6130642587bc1d5587c2ba7154dbb0bf17a6f8168                              0.7s
 => => sha256:8e2e97c70f6bbb4dd7a45ff6130642587bc1d5587c2ba7154dbb0bf17a6f8168 1.86kB / 1.86kB                                                    0.0s
 => => sha256:507af78be1a5d6546907f4fcacfa3caccf6417c5bc122f30ad8378d9af5d2f46 3.04kB / 3.04kB                                                    0.0s
 => => sha256:d771c223ba510c0ffa7501c967b42582012cdeadc39404ffbe273ce595f57618 10.40kB / 10.40kB                                                  0.0s
 => => sha256:759700526b7894aa9c150feb2ebfcd00cf06d2890df739e71555edcfd13669e3 31.42MB / 31.42MB                                                  0.9s
 => => sha256:a8dcdddf442a45bf7f3fa4fb30fca109bc7901f0be6fb0f44a423fd5524422f9 1.80kB / 1.80kB                                                    0.6s
 => => sha256:0eecd8690f789ce329439a34ce22d7fd4037ac271a2ffba091a88136ba6a7f7e 4.41MB / 4.41MB                                                    1.0s
 => => extracting sha256:759700526b7894aa9c150feb2ebfcd00cf06d2890df739e71555edcfd13669e3                                                         4.8s
 => => sha256:48f27b3383d004360d24384835345bdcc940872aef3bf92b5c8b901bc267e588 8.05MB / 8.05MB                                                    5.7s
 => => sha256:51fc468e331656cb37acb6a783ccc90d6e36a4353ec619e7a167a93f89971d5c 1.26MB / 1.26MB                                                    5.7s
 => [musicbrainz-docker_search:3.4.2 internal] load build context                                                                                 0.2s
 => => transferring context: 197B                                                                                                                 0.0s
 => [musicbrainz-docker_search:3.4.2 1/2] FROM docker.io/metabrainz/mb-solr:3.4.2@sha256:0fd57a196f4e0411b868ca21a815f40bbbb8a8d8c5991bebc1bc901  0.0s
 => CACHED [musicbrainz-docker_search:3.4.2 2/2] COPY [ scripts/*, /usr/local/bin/ ]                                                              0.0s
 => [musicbrainz-docker-mq] exporting to image                                                                                                    3.3s
 => => exporting layers                                                                                                                           0.0s
 => => writing image sha256:d47559211dc667812210afc3816819b9e2934cc55239f3ec608545d4fca99a96                                                      0.1s
 => => naming to docker.io/library/musicbrainz-docker_search:3.4.2                                                                                0.0s
 => => writing image sha256:a5ac87340491ecae3be341cd63f8b6207620d49d8b922f322f84e9a78342ab2c                                                      0.1s
 => => naming to docker.io/library/musicbrainz-docker-mq                                                                                          0.0s
 => CACHED [musicbrainz-docker-indexer 1/4] FROM docker.io/metabrainz/python:2.7-20220421@sha256:7e4657e472f7e3aa3dc4cba51143607fea39f499c8f6109  0.1s
 => [musicbrainz-docker-musicbrainz internal] load build context                                                                                  0.4s
 => => transferring context: 1.32kB                                                                                                               0.0s
 => CACHED [musicbrainz-docker-musicbrainz  1/11] FROM docker.io/metabrainz/base-image:focal-1.0.0-alpha1@sha256:6cfbacd503983f7b63a16c4ac0bbb9a  0.0s
 => ERROR [musicbrainz-docker-indexer 2/4] RUN apt-get update     && apt-get install --no-install-recommends -qy       ca-certificates       cro  3.0s
 => [musicbrainz-docker-mq internal] load build context                                                                                           0.5s
 => => transferring context: 303B                                                                                                                 0.0s
 => [musicbrainz-docker-mq 1/2] FROM docker.io/library/rabbitmq:3.6.16-management@sha256:05bd722c6b0c747ae7f854baa9e9ceb9b47da75e39f93ad6a1db74f  0.0s
 => [musicbrainz-docker-musicbrainz  2/11] RUN curl -sSLO --retry 5 https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linu  5.7s
 => CACHED [musicbrainz-docker-mq 2/2] COPY [ scripts/*, / ]                                                                                      0.0s
------
 > [musicbrainz-docker-indexer 2/4] RUN apt-get update     && apt-get install --no-install-recommends -qy       ca-certificates       cron       gcc       git       libc6-dev       libffi-dev       libssl-dev       libpq-dev       libxslt1-dev     && rm -rf /var/lib/apt/lists/*:
#0 1.460 Reading package lists...
#0 1.477 E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)
------
failed to solve: executor failed running [/bin/sh -c apt-get update     && apt-get install --no-install-recommends -qy       ca-certificates       cron       gcc       git       libc6-dev       libffi-dev       libssl-dev       libpq-dev       libxslt1-dev     && rm -rf /var/lib/apt/lists/*]: exit code: 100
```

**Comment by yvanzo** [comment] 2023-07-12 17:21
Hi,

I tried to reproduce your issue but the service `indexer` is buiding just fine here and no change has been made to it (Dockerfile and base image) since last year.

Please make sure that it wasn’t a network transient error. Otherwise please provide version info output by commands at https://github.com/metabrainz/musicbrainz-docker#issues

**Comment by yvanzo** [comment] 2023-07-22 17:09
I’m closing as it cannot be reproduced so it was more likely a transient network error. Please reopen and provide more info if it is still current.

**Closed as completed by yvanzo** 2023-07-22 17:09 UTC
