### ISSUE TITLE
Could not resize shared memory segment: No space left on device

### ISSUE THREAD

**Issue by PeterCodar** [metabrainz/musicbrainz-docker#158] opened 2020-06-02 18:23 UTC
Even a disk with 160 GB seems not be enough for the command
`sudo docker-compose exec indexer python -m sir reindex`
(executed after replication up-to-date)

> 2020-06-02 17:17:06,856: (psycopg2.OperationalError) could not resize shared memory segment "/PostgreSQL.1034353204" to 196864 bytes: No space left on device
>  [SQL: 'SELECT (SELECT array_agg(musicbrainz.artist_alias.name) AS array_agg_1 \nFROM musicbrainz.artist_alias \nWHERE musicbrainz.artist_alias.artist = musicbrainz.artist.id AND musicbrainz.artist_alias.primary_for_locale = true) AS anon_1, musicbrainz.artist.type AS musicbrainz_artist_type, musicbrainz.artist.area AS musicbrainz_artist_area, musicbrainz.artist.gender AS musicbrainz_artist_gender, musicbrainz.artist.begin_area AS musicbrainz_artist_begin_area, musicbrainz.artist.end_area AS musicbrainz_artist_end_area, musicbrainz.artist.id AS musicbrainz_artist_id, musicbrainz.artist.gid AS musicbrainz_artist_gid, musicbrainz.artist.name AS musicbrainz_artist_name, musicbrainz.artist.sort_name AS musicbrainz_artist_sort_name, musicbrainz.artist.begin_date_year AS musicbrainz_artist_begin_date_year, musicbrainz.artist.begin_date_month AS musicbrainz_artist_begin_date_month, musicbrainz.artist.begin_date_day AS musicbrainz_artist_begin_date_day, musicbrainz.artist.end_date_year AS musicbrainz_artist_end_date_year, musicbrainz.artist.end_date_month AS musicbrainz_artist_end_date_month, musicbrainz.artist.end_date_day AS musicbrainz_artist_end_date_day, musicbrainz.artist.comment AS musicbrainz_artist_comment, musicbrainz.artist.edits_pending AS musicbrainz_artist_edits_pending, musicbrainz.artist.last_updated AS musicbrainz_artist_last_updated, musicbrainz.artist.ended AS musicbrainz_artist_ended, area_1.type AS area_1_type, area_1.id AS area_1_id, area_1.gid AS area_1_gid, area_1.name AS area_1_name, area_2.type AS area_2_type, area_2.id AS area_2_id, area_2.gid AS area_2_gid, area_2.name AS area_2_name, area_3.type AS area_3_type, area_3.id AS area_3_id, area_3.gid AS area_3_gid, area_3.name AS area_3_name, artist_type_1.parent AS artist_type_1_parent, artist_type_1.id AS artist_type_1_id, artist_type_1.name AS artist_type_1_name, artist_type_1.gid AS artist_type_1_gid, gender_1.parent AS gender_1_parent, gender_1.id AS gender_1_id, gender_1.name AS gender_1_name \nFROM musicbrainz.artist LEFT OUTER JOIN musicbrainz.area AS area_1 ON area_1.id = musicbrainz.artist.area LEFT OUTER JOIN musicbrainz.area AS area_2 ON area_2.id = musicbrainz.artist.begin_area LEFT OUTER JOIN musicbrainz.area AS area_3 ON area_3.id = musicbrainz.artist.end_area LEFT OUTER JOIN musicbrainz.artist_type AS artist_type_1 ON artist_type_1.id = musicbrainz.artist.type LEFT OUTER JOIN musicbrainz.gender AS gender_1 ON gender_1.id = musicbrainz.artist.gender \nWHERE musicbrainz.artist.id >= %(id_1)s AND musicbrainz.artist.id < %(id_2)s'] [parameters: {'id_2': 31308, 'id_1': 7646}]
> Traceback (most recent call last):
>   File "sir/indexing.py", line 191, in _index_entity_process_wrapper
>     return index_entity(*args)
>   File "sir/indexing.py", line 218, in index_entity
>     _query_database(entity_name, condition, data_queue)
>   File "sir/indexing.py", line 258, in _query_database
>     for row in query:
>   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2515, in __iter__
>     return self._execute_and_instances(context)
>   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2530, in _execute_and_instances
>     result = conn.execute(querycontext.statement, self._params)
>   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
>     return meth(self, multiparams, params)
>   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
>     return connection._execute_clauseelement(self, multiparams, params)
>   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
>     compiled_sql, distilled_params
>   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
>     context)
>   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1332, in _handle_dbapi_exception
>     exc_info
>   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
>     reraise(type(exception), exception, tb=exc_tb)
>   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
>     context)
>   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
>     cursor.execute(statement, parameters)
>

**Comment by brady1408** [comment] 2020-06-04 21:42
Looks like another duplicate of [150#](https://github.com/metabrainz/musicbrainz-docker/issues/150#issuecomment-630892212)

**Comment by yvanzo** [comment] 2020-06-15 21:59
Fixed in release [v-2020-06-15](https://github.com/metabrainz/musicbrainz-docker/releases/tag/v-2020-06-15).

**Closed as completed by yvanzo** 2020-06-15 21:59 UTC
