### ISSUE TITLE
Failed to import artist with id in bounds

### ISSUE THREAD

**Issue by PeterCodar** [metabrainz/musicbrainz-docker#159] opened 2020-06-02 18:34 UTC
The reindex-process seems to start successful for annotations and areas, but for artists I get the following errors:

**2020-06-02 17:17:06,855: Failed to import artist with id in bounds (7646, 31308)
2020-06-02 17:17:06,858: Failed to import artist with id in bounds (43374, 53259)
2020-06-02 17:17:06,860: Failed to import artist with id in bounds (31308, 43374**

Log until the "[No space left on device](https://github.com/metabrainz/musicbrainz-docker/issues/158)" error occurs:
> ubuntu@ubuntu:~/musicbrainz-docker$ sudo docker-compose exec indexer python -m sir reindex
> 2020-06-02 17:14:53,271: Checking whether the versions of the Solr cores are supported
> 2020-06-02 17:14:53,333: Importing annotation...
> 2020-06-02 17:16:38,240: Successfully imported annotation!
> 2020-06-02 17:16:39,127: Importing area...
> 2020-06-02 17:17:06,084: Successfully imported area!
> 2020-06-02 17:17:06,162: Importing artist...
**> 2020-06-02 17:17:06,855: Failed to import artist with id in bounds (7646, 31308)
> 2020-06-02 17:17:06,858: Failed to import artist with id in bounds (43374, 53259)
> 2020-06-02 17:17:06,860: Failed to import artist with id in bounds (31308, 43374)**
> 2020-06-02 17:17:06,856: (psycopg2.OperationalError) could not resize shared memory segment "/PostgreSQL.1034353204" to 196864 bytes: No space left on device
>  [SQL: 'SELECT (SELECT array_agg(musicbrainz.artist_alias.name) AS array_agg_1 \nFROM musicbrainz.artist_alias \nWHERE musicbrainz.artist_alias.artist = musicbrainz.artist.id AND musicbrainz.artist_alias.primary_for_locale = true) AS anon_1, musicbrainz.artist.type AS musicbrainz_artist_type, musicbrainz.artist.area AS musicbrainz_artist_area, musicbrainz.artist.gender AS musicbrainz_artist_gender, musicbrainz.artist.begin_area AS musicbrainz_artist_begin_area, musicbrainz.artist.end_area AS musicbrainz_artist_end_area, musicbrainz.artist.id AS musicbrainz_artist_id, musicbrainz.artist.gid AS musicbrainz_artist_gid, musicbrainz.artist.name AS musicbrainz_artist_name, musicbrainz.artist.sort_name AS musicbrainz_artist_sort_name, musicbrainz.artist.begin_date_year AS musicbrainz_artist_begin_date_year, musicbrainz.artist.begin_date_month AS musicbrainz_artist_begin_date_month, musicbrainz.artist.begin_date_day AS musicbrainz_artist_begin_date_day, musicbrainz.artist.end_date_year AS musicbrainz_artist_end_date_year, musicbrainz.artist.end_date_month AS musicbrainz_artist_end_date_month, musicbrainz.artist.end_date_day AS musicbrainz_artist_end_date_day, musicbrainz.artist.comment AS musicbrainz_artist_comment, musicbrainz.artist.edits_pending AS musicbrainz_artist_edits_pending, musicbrainz.artist.last_updated AS musicbrainz_artist_last_updated, musicbrainz.artist.ended AS musicbrainz_artist_ended, area_1.type ....

**Comment by brady1408** [comment] 2020-06-04 21:35
This is a problem with the default shared memory value in docker, I had the same issue and resolved it by adding a shm_size line to my docker-compose.yml to match the size of what is configured inside of postgres

[This](https://stackoverflow.com/questions/56751565/pq-could-not-resize-shared-memory-segment-no-space-left-on-device) thead was helpful in resolving this for me

Code Snip
```yaml
services:
  db:
    build:
      context: build/postgres
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION:-12}
    image: musicbrainz-docker_db:${POSTGRES_VERSION:-12}
    shm_size: 2g
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    restart: unless-stopped
    command: postgres -c "shared_buffers=2048MB" -c "shared_preload_libraries=pg_amqp.so"
```

**Comment by JoshDi** [comment] 2020-06-04 21:39
> This is a problem with the default shared memory value in docker, I had the same issue and resolved it by adding a shm_size line to my docker-compose.yml to match the size of what is configured inside of postgres
> 
> ```yaml
> services:
>   db:
>     build:
>       context: build/postgres
>       args:
>         - POSTGRES_VERSION=${POSTGRES_VERSION:-12}
>     image: musicbrainz-docker_db:${POSTGRES_VERSION:-12}
>     shm_size: 2g
>     logging:
>       driver: "json-file"
>       options: ...
> ```

Yes, shm_size needs to be set. I reported this here: [#150](https://github.com/metabrainz/musicbrainz-docker/issues/150#issuecomment-630892212)

**Comment by PeterCodar** [comment] 2020-06-04 22:01
If I understand you both @brady1408 and @JoshDi I have to set the same value for `shm_size:` in the file `docker-compose.yml` as I choose for 
`shared_buffers=` 
and
`SOLR_HEAP=`
in the memory-settings.yml [file](https://github.com/metabrainz/musicbrainz-docker#modify-memory-settings)?

What, if they use not the same value? Which value should I choose for `shm_size:`?
Or do they have to use all the same value?

**Comment by JoshDi** [comment] 2020-06-04 22:49
> If I understand you both @brady1408 and @JoshDi I have to set the same value for `shm_size:` in the file `docker-compose.yml` as I choose for
> `shared_buffers=`
> and
> `SOLR_HEAP=`
> in the memory-settings.yml [file](https://github.com/metabrainz/musicbrainz-docker#modify-memory-settings)?
> 
> What, if they use not the same value? Which value should I choose for `shm_size:`?
> Or do they have to use all the same value?

How much memory do you have on your machine? 4g and 16 threads (in my indexer.ini) for live indexing, uses about 25gb of ram.

**Comment by brady1408** [comment] 2020-06-04 23:52
This isn't a problem with solr it's actually a problem in the postgres as it pulls data from the database to be indexed, as you can see above my postgres has shared buffers set to 2G
`command: postgres -c "shared_buffers=2048MB" -c "shared_preload_libraries=pg_amqp.so"`
for this reason I went ahead and added the shm_size to the postgres container to match the shared buffer size 
`shm_size: 2g`

I updated my code snip above to show more of my docker-compose.yml so hopefully it's more obvious what I had to do.

**Comment by yvanzo** [comment] 2020-06-06 11:57
This is indeed caused by a chance in Postgres 10+ which uses `shm` for parallelism while the default `shm_size` for Docker container is `64MB`. We encountered the same issue in production last week and fixed it by adjusting `shm_size` too. I just opened the pull request https://github.com/metabrainz/musicbrainz-docker/pull/163 to address this issue.

**Comment by yvanzo** [comment] 2020-06-15 21:59
Fixed in release [v-2020-06-15](https://github.com/metabrainz/musicbrainz-docker/releases/tag/v-2020-06-15).

**Closed as completed by yvanzo** 2020-06-15 21:59 UTC

**Comment by yvanzo** [comment] 2020-06-15 22:12
Note: It is [**not** recommended to modify `docker-compose.yml`](https://github.com/metabrainz/musicbrainz-docker/tree/v-2020-06-15#local-changes) (or any other file tracked by git) as it can create conflicts when you follow update instructions. Instead, it is recommended to [create Docker Compose override files under `local` directory](https://github.com/metabrainz/musicbrainz-docker#docker-compose-overrides) you can enable or disable via project configuration.
