### ISSUE TITLE
Builded search index will not be used

### ISSUE THREAD

**Issue by PeterCodar** [metabrainz/musicbrainz-docker#56] opened 2017-08-02 13:02 UTC
I have created the search index with this command:
`sudo docker-compose run --rm indexer /home/search/index.sh`

But if I access the local webserver with
http://192.168.1.35:5000/search?query=madonna&type=artist&method=indexed
I only get this error:

```
HTTP ERROR 500

Problem accessing /. Reason:

    Index is currently not available for resource type ARTIST

Powered by Jetty:// 9.3.10.v20160621
```
What do I have to check or change or restart or move after the index building process?

**Comment by nicolas-vazquez** [comment] 2017-10-09 20:00
I'm experiencing same issue as well. Any ideas on this? Thanks!

**Comment by FreqSho** [comment] 2017-10-17 22:30
Hi @jsturgis . I'm working with @nicolas-vazquez and we are hoping to get some clarity on this index-building issue before the end of this month (October). We understand your excellent musicbrainz-docker is not a full-time gig, but please give us a general sense of timing as to when you might be able to offer some insights so we can manage our enthusiasm and expectations for getting this system operational. Much appreciated!

**Comment by jsturgis** [comment] 2017-10-31 21:02
Hi @FreqSho and @nicolas-vazquez I am looking into this now, I'll let you know if I find a solution.

**Comment by jsturgis** [comment] 2017-11-02 01:04
@FreqSho @nicolas-vazquez can you confirm if you ran out of disk space during the indexing? I just went through setting up a new server and I had this issue because I ran out of disk space during the indexing.

Also how much disk space do you have on your server?

**Comment by nicolas-vazquez** [comment] 2017-11-02 17:41
Hi. Thanks for your response. We have an EC2 instance with 250 GB of free space, so we did not run out of space when indexing. Do you have any more clues on this? Thanks!

**Comment by jsturgis** [comment] 2017-11-03 20:11
hmm, can you try running the index again and see if it works?
`sudo docker-compose run --rm indexer /home/search/index.sh`

**Comment by nicolas-vazquez** [comment] 2017-11-08 19:20
Hi, I just updated with the last code and run index again and I'm still getting the same error. Were you able to create a new instance and index without any issues?

**Comment by jsturgis** [comment] 2017-11-09 23:16
that is strange, did the index complete without any errors? yeah I was able to index without issues once I increased my disk space. If you open a shell in the indexer or the search container and look in the ```/home/search/indexdata``` dir you should see the indexes it created.

I wonder also if the database import did not complete fully so there is no artist data to index.

**Comment by nicolas-vazquez** [comment] 2017-11-13 23:33
Hi. Yes, inside the search container I have all indexes created. Index ran without any issues but I'm not able to perform an indexed search via the website localhost:5000 but I'm able to make a direct database search via the same website.

**Comment by jsturgis** [comment] 2017-11-29 20:11
Hi do you still have this issue?

**Comment by nicolas-vazquez** [comment] 2017-12-01 19:37
Hi, @jsturgis. Unfortunately, after attempting to reindex many times we were not able to get it working, so we decided to go directly to MusicBrainz to load their mirror server from scratch. We now have an instance working :] with auto-update crons configured. Please keep us posted on your progress. Thanks again for your help!

**Comment by jsturgis** [comment] 2017-12-01 20:39
Cool, I cannot reproduce your issue so I am going to close this but will re-open if other people hit the same problem.

**Closed as completed by jsturgis** 2017-12-01 20:39 UTC
